POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll


###
POST http://localhost:8081/meeting/slots
Content-Type: application/json 

{
    "name": "Testing",
    "projectName": "Test Project",
    "description": "Testing the site",
    "startTime": "1:00 PM",
    "endTime": "2:00 PM",
    "day": "Tuesday",
    "dayOfMonth": 15,
    "month": "August",
    "year": 2024,
     "userId": "6734b7dd939cee245e21e60a" ,
      "capstoneSupervisor": "Dr. John Doe" 
}
###
PUT http://localhost:8081/meeting/slots/6734b7dd939cee245e21e60a
Content-Type: application/json

{
    "name": "Updated Testing",
    "projectName": "Updated Test Project",
    "description": "Updated description for the project",
    "startTime": "2:00 PM",
    "endTime": "3:00 PM",
    "capstoneSupervisor": "Updated Dr. John Doe"
}


###
GET http://localhost:8081/meeting/slots
Content-Type: application/json

###
GET http://localhost:8081/meeting/slots/634edb2a16710b2cda6fb370
Content-Type: application/json

###
DELETE http://localhost:8081/meeting/slots/634edb2a16710b2cda6fb370

